// List of the Country. 
export default CountryNames = [
    "Afghanistan",
    "Sudan",
    "Burundi",
    "Mexico",
    "Cuba",
    "Serbia",
    "Monaco",
    "Bhutan",
    "Guyana",
    "South Georgia",
    "Bosnia and Herzegovina",
    "Brunei",
    "Pakistan",
    "Kenya",
    "Puerto Rico",
    "Somalia",
    "Svalbard and Jan Mayen",
    "Sierra Leone",
    "French Polynesia",
    "Azerbaijan",
    "Cook Islands",
    "Peru",
    "Bouvet Island",
    "Northern Mariana Islands",
    "Angola",
    "Republic of the Congo",
    "South Sudan",
    "Saint Martin",
    "Turkey",
    "Anguilla",
    "Saint Kitts and Nevis",
    "Aruba",
    "Turks and Caicos Islands",
    "Taiwan",
    "Sweden",
    "Liberia",
    "Venezuela",
    "United States Virgin Islands",
    "Bermuda",
    "Albania",
    "Hong Kong",
    "Luxembourg",
    "Eritrea",
    "Colombia",
    "Caribbean Netherlands",
    "Mongolia",
    "Yemen",
    "Lebanon",
    "Antigua and Barbuda",
    "Vietnam",
    "Palau",
    "Jersey",
    "Trinidad and Tobago",
    "Israel",
    "Bulgaria",
    "Portugal",
    "Gibraltar",
    "San Marino",
    "Singapore",
    "Sint Maarten",
    "Saudi Arabia",
    "Ghana",
    "Moldova",
    "Chad",
    "Antarctica",
    "United Kingdom",
    "Papua New Guinea",
    "French Southern and Antarctic Lands",
    "United States Minor Outlying Islands",
    "Belize",
    "Comoros",
    "Burkina Faso",
    "Faroe Islands",
    "Guinea",
    "India",
    "Curaçao",
    "Togo",
    "Tunisia",
    "Saint Barthélemy",
    "Indonesia",
    "Micronesia",
    "Austria",
    "Tajikistan",
    "DR Congo",
    "Mayotte",
    "Réunion",
    "Romania",
    "Qatar",
    "Lithuania",
    "China",
    "New Zealand",
    "Norfolk Island",
    "Mauritania",
    "Uzbekistan",
    "Finland",
    "Cameroon",
    "Heard Island and McDonald Islands",
    "Dominica",
    "Iceland",
    "Oman",
    "North Korea",
    "Guinea-Bissau",
    "Kosovo",
    "Vatican City",
    "Norway",
    "Palestine",
    "Cocos (Keeling) Islands",
    "Jamaica",
    "Egypt",
    "Cambodia",
    "Mauritius",
    "Gambia",
    "Equatorial Guinea",
    "Lesotho",
    "Martinique",
    "United States",
    "Western Sahara",
    "United Arab Emirates",
    "Mozambique",
    "Algeria",
    "Zambia",
    "Guatemala",
    "South Korea",
    "Kyrgyzstan",
    "Timor-Leste",
    "Åland Islands",
    "Jordan",
    "Malta",
    "Cyprus",
    "Falkland Islands",
    "Kazakhstan",
    "Botswana",
    "Saint Vincent and the Grenadines",
    "Barbados",
    "Tonga",
    "Thailand",
    "Belgium",
    "Canada",
    "Georgia",
    "Wallis and Futuna",
    "Fiji",
    "Netherlands",
    "Armenia",
    "Dominican Republic",
    "Guernsey",
    "Turkmenistan",
    "Nepal",
    "Maldives",
    "Libya",
    "Brazil"
]